### ISSUE TITLE
tests fail when run with node v12

### ISSUE THREAD

**Issue by joshuavial** [enspiral-dev-academy/authenticare#66]
It might be good to add a note to the readme that you need node v14 to run this - all the ?. syntax in client/request.js:22 was failing when running the tests under v12

**Comment by don-smith** [comment]
Oooo, good catch. To be clear, this only applies to the next version (`0.4.8`) so it's great @joshuavial caught this before it was merged into `main`. I would consider this a breaking change. So we should back out that syntax until `5.0.0`, which I hope we'll be ready to start working on instead of a `0.4.9`.

**Comment by don-smith** [comment]
I got around this in `0.4.8` by building both the frontend and backend code with Babel. Well, the tests still need Node 14, but we're sure the code will work with any version of Node going forward.
